/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientAuthedRouteImport } from './routes/_clientAuthed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientAuthedTanstackQueryRouteImport } from './routes/_clientAuthed/tanstack-query'
import { Route as ClientAuthedStoreRouteImport } from './routes/_clientAuthed/store'
import { Route as ClientAuthedDrizzleRouteImport } from './routes/_clientAuthed/drizzle'
import { Route as ClientAuthedStartServerFuncsRouteImport } from './routes/_clientAuthed/start.server-funcs'
import { Route as ClientAuthedStartApiRequestRouteImport } from './routes/_clientAuthed/start.api-request'
import { Route as ClientAuthedApiTqTodosRouteImport } from './routes/_clientAuthed/api.tq-todos'
import { Route as ClientAuthedApiNamesRouteImport } from './routes/_clientAuthed/api.names'

const ClientAuthedRoute = ClientAuthedRouteImport.update({
  id: '/_clientAuthed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAuthedTanstackQueryRoute =
  ClientAuthedTanstackQueryRouteImport.update({
    id: '/tanstack-query',
    path: '/tanstack-query',
    getParentRoute: () => ClientAuthedRoute,
  } as any)
const ClientAuthedStoreRoute = ClientAuthedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => ClientAuthedRoute,
} as any)
const ClientAuthedDrizzleRoute = ClientAuthedDrizzleRouteImport.update({
  id: '/drizzle',
  path: '/drizzle',
  getParentRoute: () => ClientAuthedRoute,
} as any)
const ClientAuthedStartServerFuncsRoute =
  ClientAuthedStartServerFuncsRouteImport.update({
    id: '/start/server-funcs',
    path: '/start/server-funcs',
    getParentRoute: () => ClientAuthedRoute,
  } as any)
const ClientAuthedStartApiRequestRoute =
  ClientAuthedStartApiRequestRouteImport.update({
    id: '/start/api-request',
    path: '/start/api-request',
    getParentRoute: () => ClientAuthedRoute,
  } as any)
const ClientAuthedApiTqTodosRoute = ClientAuthedApiTqTodosRouteImport.update({
  id: '/api/tq-todos',
  path: '/api/tq-todos',
  getParentRoute: () => ClientAuthedRoute,
} as any)
const ClientAuthedApiNamesRoute = ClientAuthedApiNamesRouteImport.update({
  id: '/api/names',
  path: '/api/names',
  getParentRoute: () => ClientAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drizzle': typeof ClientAuthedDrizzleRoute
  '/store': typeof ClientAuthedStoreRoute
  '/tanstack-query': typeof ClientAuthedTanstackQueryRoute
  '/api/names': typeof ClientAuthedApiNamesRoute
  '/api/tq-todos': typeof ClientAuthedApiTqTodosRoute
  '/start/api-request': typeof ClientAuthedStartApiRequestRoute
  '/start/server-funcs': typeof ClientAuthedStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drizzle': typeof ClientAuthedDrizzleRoute
  '/store': typeof ClientAuthedStoreRoute
  '/tanstack-query': typeof ClientAuthedTanstackQueryRoute
  '/api/names': typeof ClientAuthedApiNamesRoute
  '/api/tq-todos': typeof ClientAuthedApiTqTodosRoute
  '/start/api-request': typeof ClientAuthedStartApiRequestRoute
  '/start/server-funcs': typeof ClientAuthedStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_clientAuthed': typeof ClientAuthedRouteWithChildren
  '/_clientAuthed/drizzle': typeof ClientAuthedDrizzleRoute
  '/_clientAuthed/store': typeof ClientAuthedStoreRoute
  '/_clientAuthed/tanstack-query': typeof ClientAuthedTanstackQueryRoute
  '/_clientAuthed/api/names': typeof ClientAuthedApiNamesRoute
  '/_clientAuthed/api/tq-todos': typeof ClientAuthedApiTqTodosRoute
  '/_clientAuthed/start/api-request': typeof ClientAuthedStartApiRequestRoute
  '/_clientAuthed/start/server-funcs': typeof ClientAuthedStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drizzle'
    | '/store'
    | '/tanstack-query'
    | '/api/names'
    | '/api/tq-todos'
    | '/start/api-request'
    | '/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drizzle'
    | '/store'
    | '/tanstack-query'
    | '/api/names'
    | '/api/tq-todos'
    | '/start/api-request'
    | '/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/_clientAuthed'
    | '/_clientAuthed/drizzle'
    | '/_clientAuthed/store'
    | '/_clientAuthed/tanstack-query'
    | '/_clientAuthed/api/names'
    | '/_clientAuthed/api/tq-todos'
    | '/_clientAuthed/start/api-request'
    | '/_clientAuthed/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientAuthedRoute: typeof ClientAuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_clientAuthed': {
      id: '/_clientAuthed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ClientAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_clientAuthed/tanstack-query': {
      id: '/_clientAuthed/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/tanstack-query'
      preLoaderRoute: typeof ClientAuthedTanstackQueryRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
    '/_clientAuthed/store': {
      id: '/_clientAuthed/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof ClientAuthedStoreRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
    '/_clientAuthed/drizzle': {
      id: '/_clientAuthed/drizzle'
      path: '/drizzle'
      fullPath: '/drizzle'
      preLoaderRoute: typeof ClientAuthedDrizzleRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
    '/_clientAuthed/start/server-funcs': {
      id: '/_clientAuthed/start/server-funcs'
      path: '/start/server-funcs'
      fullPath: '/start/server-funcs'
      preLoaderRoute: typeof ClientAuthedStartServerFuncsRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
    '/_clientAuthed/start/api-request': {
      id: '/_clientAuthed/start/api-request'
      path: '/start/api-request'
      fullPath: '/start/api-request'
      preLoaderRoute: typeof ClientAuthedStartApiRequestRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
    '/_clientAuthed/api/tq-todos': {
      id: '/_clientAuthed/api/tq-todos'
      path: '/api/tq-todos'
      fullPath: '/api/tq-todos'
      preLoaderRoute: typeof ClientAuthedApiTqTodosRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
    '/_clientAuthed/api/names': {
      id: '/_clientAuthed/api/names'
      path: '/api/names'
      fullPath: '/api/names'
      preLoaderRoute: typeof ClientAuthedApiNamesRouteImport
      parentRoute: typeof ClientAuthedRoute
    }
  }
}

interface ClientAuthedRouteChildren {
  ClientAuthedDrizzleRoute: typeof ClientAuthedDrizzleRoute
  ClientAuthedStoreRoute: typeof ClientAuthedStoreRoute
  ClientAuthedTanstackQueryRoute: typeof ClientAuthedTanstackQueryRoute
  ClientAuthedApiNamesRoute: typeof ClientAuthedApiNamesRoute
  ClientAuthedApiTqTodosRoute: typeof ClientAuthedApiTqTodosRoute
  ClientAuthedStartApiRequestRoute: typeof ClientAuthedStartApiRequestRoute
  ClientAuthedStartServerFuncsRoute: typeof ClientAuthedStartServerFuncsRoute
}

const ClientAuthedRouteChildren: ClientAuthedRouteChildren = {
  ClientAuthedDrizzleRoute: ClientAuthedDrizzleRoute,
  ClientAuthedStoreRoute: ClientAuthedStoreRoute,
  ClientAuthedTanstackQueryRoute: ClientAuthedTanstackQueryRoute,
  ClientAuthedApiNamesRoute: ClientAuthedApiNamesRoute,
  ClientAuthedApiTqTodosRoute: ClientAuthedApiTqTodosRoute,
  ClientAuthedStartApiRequestRoute: ClientAuthedStartApiRequestRoute,
  ClientAuthedStartServerFuncsRoute: ClientAuthedStartServerFuncsRoute,
}

const ClientAuthedRouteWithChildren = ClientAuthedRoute._addFileChildren(
  ClientAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientAuthedRoute: ClientAuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
